include('publicity.pl').
%/facts section here/
company(reil, it, ssi, 10000, websites, india ,jaipur).
company(girnar, it, ssi, 10000, websites, india, bangalore).
company(rajcom, it, msi, 20000, websites, india, bangalore).
company(infoedge, it, ssi, 10000, websites, india ,jaipur).
company(growus, it, ssi, 10000, websites, india, bangalore).
company(spark, it, msi, 20000, websites, india, bangalore).
company(godaddy,it,lsi,25000,websites,india,bangalore).
company(c,it,lsi,30000,market,india,bangalore).
company(d,it,ssi,20000,market,india,delhi).
company(e,it,msi,30000,market,india,delhi).
company(f,it,lsi,70000,market,india,delhi).
company(f1,it,lsi,50000,market,india,delhi).
company(f0,it,lsi,0,market,india,delhi).
company(g,it,ssi,6000,market,bangladesh,dhaka).
company(g1,it,ssi,6500,market,bangladesh,dhaka).
company(h,it,msi,7000,market,bangladesh,dhaka).
company(i,it,lsi,10000,market,bangladesh,dhaka).


%/company financial condition starts in dollars & growth rate/
financial_company(reil,55000,1).
financial_company(girnar,5000,15.5).
financial_company(rajcom,30000,1.5).
financial_company(godaddy,45200,3.5).
financial_company(infoedge,7000,5.5).
financial_company(growus,40000,1.5).
financial_company(spark,50000,1.5).


%/company credibility condition  in functional years & reputation score of 100 according to   Sources: Harris Interactive /
credibility_company(reil,10,63).
credibility_company(girnar,3,45).
credibility_company(rajcom,20,80).
credibility_company(godaddy,10,5).
credibility_company(infoedge,3,65).
credibility_company(growus,2,80).
credibility_company(spark,1,71).




budget(it, india, ssi, 3000).
budget(it, india, msi, 6000).
budget(it, india, lsi, 9000).
budget(manufacture, india, ssi, 10000).
budget(manufacture, india, msi, 30000).
budget(manufacture, india, lsi, 50000).

budget(it, bangladesh, ssi, 1000).
budget(it, bangladesh, msi, 3000).
budget(it, bangladesh, lsi, 5000).
budget(manufacture, bangladesh, ssi, 2500).
budget(manufacture, bangladesh, msi, 4000).
budget(manufacture, bangladesh, lsi, 6000).

%/city(city , country, per capita,airport)./
city(jaipur, india, 1000, yes).
city(delhi, india, 6000, yes).
city(bangalore, india, 3000, no).
city(noida, india, 7000, no).
city(chennai, india, 5000, yes).

city(dhaka, bangladesh, 7000, no).
city(mirpur, bangladesh, 4000, no).

nearairport(bangalore, 100).
nearairport(noida, 45).

nearairport(dhaka, 70).

metro(delhi).
metro(bangalore).
metro(chennai).

metro(dhaka).

%/ sentence section starts here/
print_metro('Rating of City on basis of Facilties  is '). 
print_income('Rating of City on basis of Per Capita Income is ').
%/ sentence section ends here/



%/facts section ends here/

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/COIDING START HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%






feasiblity(Name,Type,Scale,Budget,Market,Country,City) :-
%/Consult publicity_tv.pl file and call HOLA query/
%/consult(publicity_tv),hola,/

%/insert in Competition_Financial_Rating.txt file/
tell('Competition_Financial_Rating.txt'),  write('COMPETITION FINANCIAL RATING'),nl,nl,told,
tell('tophp.txt'),told,
tell('tophp2.txt'),told,
%/insert in report.txt file/
tell('report.txt'),
write('FEASIBILITY STUDY'),nl,
write('Generated by BIZ - MO v1.0'),nl,
write('You Entered / Changed to the following Values'),nl,write(Name),nl,write(Type),nl,write(Scale),nl,write(Budget),nl,write(Market),nl,write(Country),nl,write(City),nl,told,
%/Competition_Financial_Rating.txt file told/

write('You Entered / Changed to the following Values'),nl,write(Name),nl,write(Type),nl,write(Scale),nl,write(Budget),nl,write(Market),nl,write(Country),nl,write(City),nl,
asserta(c_name(Name)),
asserta(c_type(Type)),
asserta(c_scale(Scale)),
asserta(c_budget(Budget)),
asserta(c_market(Market)),
asserta(c_country(Country)),
asserta(c_city(City)),

%/functions for feasiblity/
checkprevious(Name,Country),      
checkbudget(Type,Country,Scale,Budget),
geofeasiblity(Type,Scale,Country,City),
ecofeasiblity(Type,Scale,Market,Country,City).
%/functions for feasiblity ends here/

%/previous functions/
checkprevious(Name,Country) :-
nl,write('CALLING FUNCTION CHECK PREVIOUS CHECK .....'),nl,
(company(Name,_,_,_,_,Country,_)->nl,nl,branch(Country);new(Country)),
nl,write('LEAVING FUNCTION CHECK PREVIOUS CHECK .....'),nl.
%/previous  functions end here/


%/branch functions/
branch(C):-
nl,write('CALLING FUNCTION CHECK BRANCH....'),nl,
write('Are you  looking for a branch in '),
ask(C)->(write('YOU ARE ALLOWED TO PROCEED WITH SYSTEM .......')),nl;(write('sorry company already exist EXITING SYSTEM .......'),changecountry),
nl,write('LEAVING FUNCTION CHECK BRANCH.....'),nl.
%/branch functions end here/

%/Change Country from here/
changecountry :-
nl,write('CHANGING YOUR COUNTRY.....'),nl,
write('please enter the name of updated country'),write(':'),
read(CC),write(CC),
append('report.txt'),write('updated country : '),write(CC),told,
retract(c_country(Country)),
asserta(c_country(CC)),
append('report.txt'),nl,write('Updating System...'),nl,write('Restarting study ....'),nl,told,
nl,write('Updating System...'),nl,write('Restarting study ....'),nl,
nl,write(' YOUR COUNTRY HAS BEEN UPDATED ........... SYSTEM RESTARTING.....'),nl,change.
%/Change Country end here Since country is changing City must be changed/



%/Change City/
change :-
append('report.txt'),nl,write('CHANGING YOUR CITY.....'),nl,told,
nl,write('CHANGING YOUR CITY.....'),nl,
write('Please Enter the name of update city'),write(':'),
read(CT),write(CT),
append('report.txt'),write('updated city : '),write(CT),told,
retract(c_city(City)),
asserta(c_city(CT)),write(CT),
c_name(N),                                       %/this simply implies that the name comes in asserted value of c_name comes in N/
c_type(T),
c_scale(S),
c_budget(B),
c_market(M),
c_country(CC),write(CC),

append('report.txt'),nl,write('Updating System...'),nl,write('Restarting study ....'),nl,told,
nl,write('Updating System...'),nl,write('Restarting study ....'),nl,
nl,write(' YOUR CITY HAS BEEN UPDATED ........... SYSTEM RESTARTING.....'),nl,
fail.   % /this functions calls the feasiblity again with both results equals to fail/ 
%/Change City/

%/new functions/
new(C):-
nl,write('CALLING FUNCTION NEW .....'),nl,
write('CHECKING COUNTRY :'),write(C),nl,write('LEAVING FUNCTION NEW .....'),nl.
%/new functions end here/

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%?/NAME CHECKING LOOP ENDS HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%/check budget functions/
checkbudget(Type,Country,Scale,Budget) :-
Total is 1,
nl,write('CALLING FUNCTION CHECK BUDGET .....'),nl,
nl,write('Your Current Budget is: '),write(Budget),
append('report.txt'),nl,write('Your Current Budget is: '),write(Budget),told,
budget(Type,Country,Scale,Price),
nl,write('THRESHOLD BUDGET IS: '),write(Price),nl,
append('report.txt'),nl,write('THRESHOLD BUDGET IS: '),write(Price),nl,told,

((3*Price)<Budget->append('report.txt'),write('budget rating A'),told,write('budget rating A');(2*Price)<Budget->append('report.txt'),write('budget rating B'),told,write('budget rating B');Price<Budget->append('report.txt'),write('budget rating C'),told,write('budget rating C');updatebudget(Type,Country,Scale)),
nl,write('LEAVING FUNCTION CHECK BUDGET .....'),nl.
%/check budget functions/


%/budget_rating functions/
budgetrating(Type,Scale,Country,Budget):- 
write('CALLING FUNCTION BUDGET RATING .....'),nl,c_city(City),write(City),
(company(_,Type,Scale,P,_,Country,City),Budget>P->append('report.txt'),write('BUDET RATING A  .....'),told,write('BUDET RATING A  .....');((P-Budget)<(Budget/2))->append('report.txt'),write('BUDET RATING B .....'),told,write('BUDET RATING B .....');append('report.txt'),write('BUDET RATING C .....'),told,write('BUDET RATING C .....')),% /bad way of writing things/
nl,write('LEAVING FUNCTION  BUDGET RATING .....'),nl.
%/budget_rating functions end here/


%/budget update functions/
updatebudget(T,C,S) :-
nl,write('CALLING FUNCTION  UPDATE BUDGET.....'),nl,
nl,write('Your Budget is not satisfactory for given location please update it'), 
read(NB),
retract(c_budget(Budget)),
asserta(c_budget(NB)),
append('report.txt'),nl,write('Your Budget is not satisfactory for given location :updated budget is'),write(NB),told,
checkbudget(T,C,S,NB),
nl,write('CALLING FUNCTION UPDATE BUDGET.....'),nl.
%/budget  update functions end here/

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/BUDGET CHECKING LOOP ENDS HERE /%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%/geaofeasiblity starts here/
geofeasiblity(Type,Scale,Country,City):-
nl,write('CALLING FUNCTION GEOGRAPHICAL FEASIBILITY .....'),nl,
(Type==it->geo_it(Scale,Country,City);Type==manufacture->geo_manufacture(Scale,Country,City);append('report.txt'),write('type not match'),told,write('type not match')),
nl,write('LEAVING FUNCTION GEOGRAPHICAL FEASIBILITY .....'),nl.
%/geaofeasiblity  ends here/


%/Geo Information technology functions/
geo_it(Scale,Country,City) :-
nl,write('CALLING FUNCTION GEOGRAPHICAL FEASIBILITY INFORMATION TECHNOLOGY .....'),nl,
checkrating(Scale,City,Rating),
transport(Scale,Country,City),
nl,write('LEAVING FUNCTION GEOGRAPHICAL FEASIBILITY INFORMATION TECHNOLOGY .....'),nl.
%/Geo Information technology functions ends here/


%/Rating Function functions/
checkrating(Scale,City,Rating) :-
append('report.txt'),nl,write('CALLING FUNCTION CITY RATING.....'),nl,print_metro(A),print_income(B),told,
nl,write('CALLING FUNCTION CITY RATING.....'),nl,print_metro(A),print_income(B),
(metro(City)->P=10,append('report.txt'),nl,write(A),nl,write(P),told,nl,write(A),nl,write(P);P=5,append('report.txt'),nl,write(A),nl,write(P),told,nl,write(A),nl,write(P)),
(city(City,_,Capita,_),Capita >5000->N=10,append('report.txt'),nl,write(B),nl,write(N),told,nl,write(B),nl,write(N);N=5,nl,append('report.txt'),write(B),nl,write(N),told,write(B),nl,write(N)), %/hey there can be a BUG remind :P let us throw it out/
(Avg is (N+P)/2),nl,write('Calculated Rating Of City is' ),nl,write(Avg),append('report.txt'),nl,write('Calculated Rating Of City is' ),nl,write(Avg),told,
((Avg==10->append('report.txt'),nl,write('your city raitng is A , results are excellent'),told,nl,write('your city raitng is A , results are excellent');Avg==7.5->append('report.txt'),write('your city raitng is B , results are moderate'),told,write('your city raitng is B , results are moderate');Avg==5->append('report.txt'),write('your City Rating is C or below do you want to change'),told,write('your City Rating is C or below do you want to change'),change;nl)),
nl,write('LEAVING FUNCTION CITY RATING.....'),nl,append('report.txt'),nl,write('LEAVING FUNCTION CITY RATING.....'),nl,told.
%/Rating functions ends here/

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/CITY RATING FUNCTION ENDS HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%/transport start here/
transport(Scale,Country,City):-
c_type(Type),
nl,write('CALLING FUNCTION TRANSPORT DYNAMIC CHECK .....'),nl,
(Type==it->airportcheck(City,Type,Scale);
Type==manufacture->nl;nl,append('report.txt'),write('type not match'),told,write('type not match')),
nl,write('LEAVING FUNCTION TRANSPORT DYNAMIC CHECK .....'),nl.
%/transport ends here/



%/airport check start here/
airportcheck(City,Type,Scale):-
append('report.txt'),nl,write('CALLING FUNCTION AIRPORT CHECKING.....'),nl,write(City),told,
nl,write('CALLING FUNCTION AIRPORT CHECKING.....'),nl,write(City),
(((Scale==msi),(city(City,_,_,P),P==yes->nl,append('report.txt'),nl,write('Airport Requirement Met'),told,write('Airport Requirement Met');nl,near_airport(City)));
((Scale==lsi),(city(City,_,_,P),P==yes->nl,append('report.txt'),nl,write('Airport Requirement Met'),told,write('Airport Requirement Met');append('report.txt'),nl,write('Airport Requirement didnt met'),told,nl,write('Airport Requirement didnt met'),change))),%/dynamicity introduced here/
nl,write('LEAVING FUNCTION AIRPORT CHECKING .....'),nl,append('report.txt'),nl,write('LEAVING FUNCTION AIRPORT CHECKING .....'),nl,told.
%/airport check here/


%/near airport check start here/
near_airport(City) :-
append('report.txt'),nl,write('CALLING FUNCTION AIRPORT  NEAR CHECKING.....'),nl,told,nl,write('CALLING FUNCTION AIRPORT  NEAR CHECKING.....'),nl,
((nearairport(City,P),append('report.txt'),nl,write('Proposed Nearest Airport Distance '),write(P),nl,told,nl,write('Proposed Nearest Airport Distance '),write(P),nl,write('will your firm be satisfied with it ?'),read(A),A==yes->nl;change)),
nl,write('LEAVING FUNCTION AIRPORT  NEAR CHECKING.....'),nl,append('report.txt'),nl,write('LEAVING FUNCTION AIRPORT  NEAR CHECKING.....'),nl,told.
%/near airport check here/


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/GEOGRAPHICAL INFORMATION TECHNOLOGY ENDS HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%/Geo Manufacture functions/
geo_manufacture(Scale,Country,City) :-
nl,write('CALLING FUNCTION GEOGRAPHICAL FEASIBILITY MANUFACTURING .....'),nl,
transport(Scale,Country,City),
nl,write('LEAVING FUNCTION GEOGRAPHICAL FEASIBILITY INFORMATION TECHNOLOGY .....'),nl.
%/Geo Manufature functions ends here/






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/GEOGRAPHICAL FEASBILITY ENDS HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%/ecoofeasiblity starts here/
ecofeasiblity(Type, Scale, Market, Country, City):-
nl,write('CALLING FUNCTION ECONOMIC FEASIBILITY .....'),nl,
check_comptetion(Type, Scale, Market, Country, City),
nl,write('LEAVING FUNCTION ECONOMIC FEASIBILITY .....'),nl.
%/ecoofeasiblity  ends here/



%/comptetion starts here/
check_comptetion(Type, Scale, Market, Country, City):-
%/insert Financial Competition bureau in Competition_Financial_Rating.txt file/
append('Competition_Financial_Rating.txt'),nl,nl,
nl,write('Your chief Competitors according to our software are :'),
told,

nl,write('CALLING FUNCTION COMPTETION FEASIBILITY .....'),
nl,write('Your chief Competitors according to our software are :'),
findall(Name,company(Name,_,_,_,Market,_,_),Bag),
write(Bag),nl,nl,

append('Competition_Financial_Rating.txt'),nl,nl,
write(Bag),nl,nl,
told,

finanalysis(Bag,F),write('overall finance competition points are : '),write(F),nl,
sizelist(Bag,Size),write('total number of competitors are :'),write(Size),
nl,nl,nl,write('CALCULATED FINANCIAL COMPETITION FINAL IS :'),Final is F/Size,write(Final),nl,nl,                                                       %/color/

write('[Note :Calculations below based on the Data from Forbes Magzine Company rating 2010 -2011]'),nl,


append('Competition_Financial_Rating.txt'),nl,nl,

write('overall finance competition points are : '),write(F),nl,
write('total number of competitors are :'),write(Size),
nl,nl,nl,write('CALCULATED FINANCIAL COMPETITION FINAL IS :'),Final is F/Size,write(Final),nl,nl,                                                       %/color/
write('[Note :Calculations below based on the Data from Forbes Magzine Company rating 2010 -2011]'),nl,
told,



credibility_analysis(Bag,C),nl,nl,nl,write('overall credebility points of competitors are :'),write(C),nl,
nl,nl,nl,write('CALCULATED CERDIBILITY COMPETITION FINAL IS :'),FinalC is C/Size,write(FinalC),nl,nl,                                                       %/color/

append('Competition_Financial_Rating.txt'),nl,nl,
write('overall credebility points of competitors are :'),write(C),nl,
nl,nl,nl,write('CALCULATED CERDIBILITY COMPETITION FINAL IS :'),FinalC is C/Size,write(FinalC),nl,nl,                                                       %/color/
told,


nl,write('LEAVING FUNCTION COMPETTION FEASIBILITY .....'),nl.
%/compltetion  ends here/


finanalysis([H|T],F):-

financial_company(H,Equity,Growth),
write('the current equity of the company  :'),write(H),write(' is '),write(Equity),nl,
write('the current fiscal growth rate of the company :'),write(H),write(' is '),write(Growth),nl,
write('calculated financial factor is :'),Product is Equity*Growth,write(Product),nl,
(Product>150000 -> write('Financial condition of  '),write(H),write(' is : A'),F1 is 10,nl;Product>70000->write('Financial condition of '),write(H),write(' is : B+'),F1 is 8.5,nl;Product>50000->write('Financial condition of '),write(H),write(' is : B'),F1 is 7,nl;Product>30000->write('Financial condition of '),write(H),write(' is : C'),F1 is 5.5),

%/insert Financial Competition bureau in Competition_Financial_Rating.txt file/
append('Competition_Financial_Rating.txt'),nl,nl,

write('the current equity of the company  :'),write(H),write(' is '),write(Equity),nl,
write('the current fiscal growth rate of the company :'),write(H),write(' is '),write(Growth),nl,
write('calculated financial factor is :'),Product is Equity*Growth,write(Product),nl,
(Product>150000 -> write('Financial condition of  '),write(H),write(' is : A'),F1 is 10,nl;Product>70000->write('Financial condition of '),write(H),write(' is : B+'),F1 is 8.5,nl;Product>50000->write('Financial condition of '),write(H),write(' is : B'),F1 is 7,nl;Product>30000->write('Financial condition of '),write(H),write(' is : C'),F1 is 5.5),


told,

%/insert Financial Competition bureau in tophp.txt file for GRAPHICAL REPORT/
append('tophp.txt'),
write(H),nl,
Product is Equity*Growth,
write(Product),nl,told,

finanalysis(T,F2),
F is F1+F2.

finanalysis([],0).

credibility_analysis([H|T],C):-
credibility_company(H,Years,Repo),nl,nl,
write('the functional years of the company  :'),write(H),write(' is '),write(Years),nl,
write('the current Reputation point of  :'),write(H),write(' is '),write(Repo),nl,
Rating is (0.2*Years+0.8*Repo)/0.8,write('The calculated rating score for company '),write(H),write(' is :'),write(Rating),nl,write('Credibility Rating of company is '),
(Rating>90 ->write('AAA+'),F1 is 10;Rating>80->write('AAA'),F1 is 9;Rating>70 ->write('A'),F1 is 7; Rating>60->write('B'), F1 is 6; Rating >0-> write('C'),F1 is 5;!),nl,nl,

append('Competition_Financial_Rating.txt'),nl,nl,
write('the functional years of the company  :'),write(H),write(' is '),write(Years),nl,
write('the current Reputation point of  :'),write(H),write(' is '),write(Repo),nl,
Rating is (0.2*Years+0.8*Repo)/0.8,write('The calculated rating score for company '),write(H),write(' is :'),write(Rating),nl,write('Credibility Rating of company is '),
(Rating>90 ->write('AAA+'),F1 is 10;Rating>80->write('AAA'),F1 is 9;Rating>70 ->write('A'),F1 is 7; Rating>60->write('B'), F1 is 6; Rating >0-> write('C'),F1 is 5;!),nl,nl,
told,


%/insert Financial Competition bureau in tophp.txt file for GRAPHICAL REPORT/
append('tophp2.txt'),
write(H),nl,
Rating is (0.2*Years+0.8*Repo)/0.8,write(Rating),nl,
told,


credibility_analysis(T,F2),

C is F1+F2.


credibility_analysis([],0).   %/PLEASE DONT FORGET ME I GIVE 'NO AS AN ANSWER'/ 






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%/CODING SECTION ENDS HERE/%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%/size of any list is calculated here/
sizelist([H|T],Size):-
sizelist(T,F1),
Size is 1+F1.
sizelist([],0).
%/size of any list is calculated here/




%/ask funtion start here/
ask(V):-
nl,write(V), 
write('? : '),
read(Y), 
Y == yes.
%/ask funtion end here/





kola:-
feasiblity(reil, it, msi, 10000, websites, bangladesh, dhaka).